{
 "title": "custom dasboard",
 "time": { "from": "2025-08-05T14:12:47.764Z", "to": "2025-08-05T14:44:42.470Z" },
 "panels": [
  {
   "title": "Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "f1" },
    { "expr": "accuracy" },
    { "expr": "precision" },
    { "expr": "recall" }
   ]
  },
  {
   "title": "Time histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "request_processing_seconds_bucket"
    }
   ]
  },
  {
   "title": "Procced samples counter",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "sample_count_total", "legendFormat": "{{label_name}}" }
   ]
  }
 ]
}